# Generated by Django 5.2.3 on 2025-06-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="years_of_experience",
        ),
    ]
