# Generated by Django 5.2.3 on 2025-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_remove_cook_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
