# Generated by Django 5.2.3 on 2025-06-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_ingredient_alter_dish_options_dish_ingredients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishtype",
            options={
                "ordering": ("name",),
                "verbose_name": "dish_type",
                "verbose_name_plural": "dish_types",
            },
        ),
        migrations.AlterModelTable(
            name="dishtype",
            table="dish_type",
        ),
    ]
