# Generated by Django 5.2.3 on 2025-06-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_alter_dishtype_options_alter_dishtype_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelTable(
            name="dishtype",
            table=None,
        ),
    ]
